// IranTour Advisor — Data v3 (no pricing, 31 provinces, complete bilingual)

// ─── Visit Purpose Categories ───────────────────────────────
const VISIT_PURPOSES = [
  { key: 'tourism',   faIcon: '🎭', fa: 'گردشگری و تفریح',     en: 'Tourism & Leisure' },
  { key: 'business',  faIcon: '💼', fa: 'سفر تجاری',             en: 'Business Trip' },
  { key: 'academic',  faIcon: '🔬', fa: 'پژوهش دانشگاهی',       en: 'Academic Research' },
  { key: 'media',     faIcon: '📸', fa: 'عکاسی و رسانه',         en: 'Photography & Media' },
  { key: 'religious', faIcon: '🕌', fa: 'سفر زیارتی',             en: 'Religious Journey' },
  { key: 'nature',    faIcon: '🌿', fa: 'طبیعت و ماجراجویی',    en: 'Nature & Adventure' },
  { key: 'arts',      faIcon: '🎨', fa: 'هنر و فرهنگ',           en: 'Arts & Culture' },
  { key: 'family',    faIcon: '👨‍👩‍👧', fa: 'سفر خانوادگی',    en: 'Family Travel' },
];

// ─── Tour Packages v3 (no pricing, multi-city, 6 highlights each) ─────────
const PACKAGES = [
  {
    id: 1,
    nameFa: 'مسیر معماری پارسی',
    nameEn: 'Persian Architecture Trail',
    cities: ['اصفهان', 'کاشان', 'یزد', 'شیراز'],
    citiesEn: ['Isfahan', 'Kashan', 'Yazd', 'Shiraz'],
    days: 10,
    difficulty: 'easy',
    rating: 4.9, reviews: 284,
    purposes: ['tourism', 'academic', 'arts', 'media'],
    gradient: 'linear-gradient(135deg, #1B3A6B 0%, #2E6B9E 40%, #8B1A1A 100%)',
    tagFa: 'معماری اسلامی',
    tagEn: 'Islamic Architecture',
    descFa: 'سفر در میان شاهکارهای معماری اسلامی ایران از میدان نقش‌جهان تا خانه‌های تاریخی کاشان، برج‌های باد یزد و مسجد نصیرالملک شیراز',
    descEn: 'Journey through Iran\'s Islamic architecture masterpieces from Naqsh-e Jahan Square to Kashan\'s historic houses, Yazd\'s wind towers, and Shiraz\'s Pink Mosque',
    highlights: ['میدان نقش‌جهان', 'خانه بروجردی‌ها', 'تخت جمشید', 'برج‌های باد', 'مسجد نصیرالملک', 'باغ فین'],
    highlightsEn: ['Naqsh-e Jahan Square', 'Borujerdi House', 'Persepolis', 'Wind Towers', 'Nasir ol-Molk Mosque', 'Fin Garden'],
  },
  {
    id: 2,
    nameFa: 'جاده ابریشم',
    nameEn: 'Silk Road Heritage Journey',
    cities: ['یزد', 'کرمان', 'خراسان جنوبی'],
    citiesEn: ['Yazd', 'Kerman', 'South Khorasan'],
    days: 8,
    difficulty: 'medium',
    rating: 4.8, reviews: 196,
    purposes: ['academic', 'tourism', 'media', 'arts'],
    gradient: 'linear-gradient(135deg, #8B4513 0%, #D4880A 50%, #2D5A27 100%)',
    tagFa: 'میراث تاریخی',
    tagEn: 'Historic Heritage',
    descFa: 'ردپای کاروان‌های باستانی در شهرهای جاده ابریشم ایران — از برج‌های باد یزد تا باغ شاهزاده کرمان',
    descEn: 'Trace ancient caravan routes through Iran\'s Silk Road cities — from Yazd\'s wind towers to Kerman\'s Shahzade Garden',
    highlights: ['برج‌های باد یزد', 'بازار وکیل کرمان', 'باغ شاهزاده', 'شهر سوخته', 'قلعه دختر بم', 'کاروانسراهای تاریخی'],
    highlightsEn: ['Yazd Wind Towers', 'Vakil Bazaar Kerman', 'Shahzade Garden', 'Shahr-e Sukhteh', 'Bam Citadel', 'Historic Caravanserais'],
  },
  {
    id: 3,
    nameFa: 'دنیای ادبیات پارسی',
    nameEn: 'Persian Literary World',
    cities: ['شیراز', 'نیشابور'],
    citiesEn: ['Shiraz', 'Nishapur'],
    days: 6,
    difficulty: 'easy',
    rating: 4.7, reviews: 143,
    purposes: ['academic', 'tourism', 'arts'],
    gradient: 'linear-gradient(135deg, #4A235A 0%, #1B3A6B 50%, #8B1A1A 100%)',
    tagFa: 'ادبیات کلاسیک',
    tagEn: 'Classical Literature',
    descFa: 'در آغوش حافظ، سعدی و خیام — سفری در قلب شعر پارسی از آرامگاه‌های شیراز تا خاک نیشابور',
    descEn: 'In the embrace of Hafez, Saadi and Khayyam — a journey into the heart of Persian poetry from Shiraz tombs to the soil of Nishapur',
    highlights: ['آرامگاه حافظ', 'آرامگاه سعدی', 'آرامگاه خیام', 'تخت جمشید', 'باغ ارم', 'بازار وکیل شیراز'],
    highlightsEn: ['Hafez Tomb', 'Saadi Tomb', 'Omar Khayyam Tomb', 'Persepolis', 'Eram Garden', 'Vakil Bazaar Shiraz'],
  },
  {
    id: 4,
    nameFa: 'شگفتی‌های کویر و تمدن‌های باستانی',
    nameEn: 'Desert Wonders & Ancient Civilizations',
    cities: ['یزد', 'دشت لوت', 'سمنان'],
    citiesEn: ['Yazd', 'Dasht-e Lut', 'Semnan'],
    days: 7,
    difficulty: 'medium',
    rating: 4.9, reviews: 228,
    purposes: ['nature', 'media', 'academic', 'tourism'],
    gradient: 'linear-gradient(135deg, #0D1B2A 0%, #1B3A6B 40%, #8B4513 100%)',
    tagFa: 'طبیعت و کویر',
    tagEn: 'Nature & Desert',
    descFa: 'شب‌های جادویی دشت لوت، معماری بومی یزد، رصد ستارگان و رازهای کویر ایران',
    descEn: 'Magical nights in Dasht-e Lut, vernacular architecture of Yazd, stargazing and the secrets of Iran\'s desert',
    highlights: ['دشت لوت', 'برج‌های باد', 'رصد ستارگان', 'آتشکده زرتشتی', 'کاروانسرای سمنان', 'بافت تاریخی یزد'],
    highlightsEn: ['Dasht-e Lut Desert', 'Wind Towers', 'Desert Stargazing', 'Zoroastrian Fire Temple', 'Semnan Caravanserai', 'Yazd Historic Fabric'],
  },
  {
    id: 5,
    nameFa: 'میراث صنعتی و مدرن ایران',
    nameEn: 'Iranian Industrial & Modern Heritage',
    cities: ['اصفهان', 'اراک', 'تهران'],
    citiesEn: ['Isfahan', 'Arak', 'Tehran'],
    days: 6,
    difficulty: 'easy',
    rating: 4.5, reviews: 89,
    purposes: ['business', 'academic', 'tourism'],
    gradient: 'linear-gradient(135deg, #1C1C1E 0%, #1B3A6B 50%, #2D5A27 100%)',
    tagFa: 'صنعت و مدرنیته',
    tagEn: 'Industry & Modernity',
    descFa: 'کشف ایران مدرن از کارخانه‌های تاریخی اراک تا گالری‌های هنری تهران و پل‌های اصفهان',
    descEn: 'Discover modern Iran from Arak\'s historic factories to Tehran\'s art galleries and Isfahan\'s bridges',
    highlights: ['گالری‌های هنری تهران', 'کارخانه‌های اراک', 'کاخ نیاوران', 'موزه ملی ایران', 'پل خواجو اصفهان', 'بازار بزرگ تهران'],
    highlightsEn: ['Tehran Art Galleries', 'Arak Industrial Heritage', 'Niavaran Palace', 'National Museum of Iran', 'Khaju Bridge Isfahan', 'Tehran Grand Bazaar'],
  },
  {
    id: 6,
    nameFa: 'جهان شیعی و اماکن مقدس',
    nameEn: 'Shia World & Religious Sites',
    cities: ['مشهد', 'قم', 'تهران'],
    citiesEn: ['Mashhad', 'Qom', 'Tehran'],
    days: 7,
    difficulty: 'easy',
    rating: 4.8, reviews: 317,
    purposes: ['religious', 'academic', 'tourism'],
    gradient: 'linear-gradient(135deg, #1A5A2A 0%, #1A7A8A 40%, #1B3A6B 100%)',
    tagFa: 'زیارتی',
    tagEn: 'Religious Pilgrimage',
    descFa: 'سفر معنوی به قلب جهان شیعه — از حرم امام رضا تا حوزه علمیه قم و مساجد تاریخی تهران',
    descEn: 'Spiritual journey to the heart of the Shia world — from Imam Reza shrine to Qom seminary and Tehran\'s historic mosques',
    highlights: ['حرم امام رضا مشهد', 'حرم حضرت معصومه', 'مسجد جمکران', 'موزه آستان قدس', 'حوزه علمیه قم', 'مسجد شاه تهران'],
    highlightsEn: ['Imam Reza Shrine Mashhad', 'Masoumeh Shrine Qom', 'Jamkaran Mosque', 'Astan Quds Museum', 'Qom Seminary', 'Shah Mosque Tehran'],
  },
];

// ─── 3 Default Guides (complete data) ────────────────────────
const GUIDES = [
  {
    id: 1,
    nameFa: 'سارا محمدی',
    nameEn: 'Sara Mohammadi',
    city: 'شیراز',
    cityEn: 'Shiraz',
    specialtyFa: 'شعر پارسی و معماری کلاسیک',
    specialtyEn: 'Persian Poetry & Classical Architecture',
    rating: 4.8, reviews: 47,
    experience: 12,
    languages: [
      { code: 'en', flag: '🇬🇧', name: 'English' },
      { code: 'fr', flag: '🇫🇷', name: 'Français' },
    ],
    bioFa: '۱۲ سال است که در کوچه‌های شیراز قدم می‌زنم و نفس شعر و معماری این شهر را می‌کشم. تورهایم حافظ و سعدی را از طریق بازدیدهای صمیمی، داستان‌سرایی و مکان‌های پنهانی که گردشگران به تنهایی هرگز نمی‌یابند، زنده می‌کند.',
    bioEn: 'I\'ve spent 12 years walking the lanes of Shiraz, breathing its poetry and architecture. My tours bring Hafez and Saadi to life through intimate visits, storytelling, and hidden spots tourists never find alone.',
    activities: [
      { fa: 'آرامگاه حافظ در غروب آفتاب', en: 'Hafez Tomb at sunset', icon: '📜' },
      { fa: 'طلوع آفتاب در مسجد نصیرالملک', en: 'Nasir ol-Molk Mosque at sunrise', icon: '🕌' },
      { fa: 'تور یک‌روزه تخت‌جمشید', en: 'Persepolis full-day trip', icon: '🏛️' },
      { fa: 'گشت سنتی بازار وکیل', en: 'Traditional Vakil Bazaar walk', icon: '🛍️' },
      { fa: 'کارگاه خوشنویسی پارسی', en: 'Persian calligraphy workshop', icon: '✍️' },
      { fa: 'تور گیاه‌شناسی باغ ارم', en: 'Eram Garden botanical tour', icon: '🌸' },
    ],
    contact: {
      email: 'sara.mohammadi.shiraz@gmail.com',
      phone: '+98 917 xxx xxxx',
      instagram: '@sara.shiraz.guide',
      telegram: '@sarashirazguide',
    },
    avatarColor: '#8B1A1A',
    carpetPattern: 'shiraz',
  },
  {
    id: 2,
    nameFa: 'رضا احمدی',
    nameEn: 'Reza Ahmadi',
    city: 'اصفهان',
    cityEn: 'Isfahan',
    specialtyFa: 'معماری اسلامی و میراث ارمنی',
    specialtyEn: 'Islamic Architecture & Armenian Heritage',
    rating: 4.9, reviews: 63,
    experience: 9,
    languages: [
      { code: 'en', flag: '🇬🇧', name: 'English' },
      { code: 'ar', flag: '🇸🇦', name: 'العربية' },
    ],
    bioFa: 'اصفهان یک شهر نیست، یک تمدن است. ۹ سال است که در اینجا راهنمایی می‌کنم و در معماری اسلامی و میراث مسیحی ارمنی محله جلفا تخصص دارم.',
    bioEn: 'Isfahan is not a city, it\'s a civilization. I\'ve been guiding here for 9 years, specializing in Islamic architecture and the Armenian Christian heritage of Jolfa district.',
    activities: [
      { fa: 'تور کامل میدان نقش‌جهان', en: 'Naqsh-e Jahan Square full tour', icon: '🏟️' },
      { fa: 'نمایش صوتی مسجد شیخ لطف‌الله', en: 'Sheikh Lotfollah Mosque acoustics demonstration', icon: '🕌' },
      { fa: 'محله ارمنی جلفا', en: 'Jolfa Armenian Quarter', icon: '⛪' },
      { fa: 'کارگاه سنتی قالی‌بافی', en: 'Traditional carpet workshop', icon: '🪡' },
      { fa: 'کاخ چهل‌ستون و نقاشی‌های دیواری', en: 'Chehel Sotoun Palace & frescoes', icon: '🏛️' },
      { fa: 'اتاق‌های موسیقی کاخ عالی‌قاپو', en: 'Ali Qapu music rooms', icon: '🎵' },
    ],
    contact: {
      email: 'reza.ahmadi.isfahan@gmail.com',
      phone: '+98 913 xxx xxxx',
      instagram: '@reza.isfahan.tours',
      telegram: '@rezaisfahanguide',
    },
    avatarColor: '#1B3A6B',
    carpetPattern: 'isfahan',
  },
  {
    id: 3,
    nameFa: 'مریم حسینی',
    nameEn: 'Maryam Hosseini',
    city: 'یزد',
    cityEn: 'Yazd',
    specialtyFa: 'تمدن باستانی کویر و فرهنگ زرتشتی',
    specialtyEn: 'Ancient Desert Civilization & Zoroastrian Culture',
    rating: 4.7, reviews: 38,
    experience: 7,
    languages: [
      { code: 'en', flag: '🇬🇧', name: 'English' },
      { code: 'de', flag: '🇩🇪', name: 'Deutsch' },
    ],
    bioFa: 'یزد قدیمی‌ترین شهر زنده زمین است. من در فرهنگ زرتشتی، معماری کویری و مهندسی باستانی بادگیرهایی که ۳۰۰۰ سال است مردم را خنک نگه داشته تخصص دارم.',
    bioEn: 'Yazd is Earth\'s oldest living city. I specialize in Zoroastrian culture, desert architecture, and the ancient wind-catcher engineering that kept people cool for 3,000 years.',
    activities: [
      { fa: 'تور مهندسی باغ دولت‌آباد و بادگیر', en: 'Dowlatabad Garden & windtower engineering tour', icon: '🌬️' },
      { fa: 'بازدید آتشکده زرتشتی', en: 'Zoroastrian Fire Temple visit', icon: '🔥' },
      { fa: 'پیاده‌روی در هزارتوی شهر قدیم', en: 'Old city labyrinth walk at dusk', icon: '🚶' },
      { fa: 'کارگاه شیرینی سنتی یزدی', en: 'Traditional Yazdi pastry making class', icon: '🍰' },
      { fa: 'رصد ستارگان در کویر (۳۵ کیلومتری)', en: 'Desert night stargazing (35km outside city)', icon: '⭐' },
      { fa: 'بازدید تاریخی از دخمه‌های سکوت', en: 'Towers of Silence historical walk', icon: '🗿' },
    ],
    contact: {
      email: 'maryam.hosseini.yazd@gmail.com',
      phone: '+98 912 xxx xxxx',
      instagram: '@maryam.yazd.guide',
      telegram: '@maryamyazdguide',
    },
    avatarColor: '#2D5A27',
    carpetPattern: 'yazd',
  },
];

// ─── Guide Reviews ────────────────────────────────────────────
const GUIDE_REVIEWS = {
  1: [
    { name: 'Carlos M.', flag: '🇪🇸', date: 'April 2025', rating: 5, text: 'Sara made Shiraz feel like home. Her knowledge of Persian poetry is extraordinary.' },
    { name: 'Fatima Al-H.', flag: '🇮🇶', date: 'March 2025', rating: 5, text: 'Perfect guide for our family. She knew exactly what we wanted to see.' },
    { name: 'Léa D.', flag: '🇫🇷', date: 'February 2025', rating: 5, text: 'Incredible experience at Persepolis. Sara\'s French was flawless.' },
  ],
  2: [
    { name: 'Ahmed K.', flag: '🇰🇼', date: 'April 2025', rating: 5, text: 'Reza\'s Arabic was perfect and his knowledge of Islamic art is unmatched.' },
    { name: 'James T.', flag: '🇬🇧', date: 'March 2025', rating: 5, text: 'Best guide I\'ve had anywhere in the world. Isfahan is stunning.' },
    { name: 'Nadia R.', flag: '🇩🇿', date: 'January 2025', rating: 4, text: 'Very professional and punctual. The carpet workshop was a highlight.' },
  ],
  3: [
    { name: 'Klaus B.', flag: '🇩🇪', date: 'April 2025', rating: 5, text: 'Maryam erklärt alles so präzise und leidenschaftlich. Absolut empfehlenswert!' },
    { name: 'Sophie W.', flag: '🇦🇺', date: 'February 2025', rating: 5, text: 'The desert stargazing was the highlight of my entire Iran trip.' },
    { name: 'Omar S.', flag: '🇯🇴', date: 'January 2025', rating: 5, text: 'Yazd is magical. Maryam made it even more so.' },
  ],
};

// ─── 31 Provinces of Iran (with English highlights) ──────────
const PROVINCES = [
  {
    id: 'tehran',
    nameFa: 'تهران',
    nameEn: 'Tehran',
    gradient: 'linear-gradient(135deg,#1C1C1E,#8B1A1A)',
    highlights: ['کاخ گلستان', 'موزه ملی', 'بازار تجریش'],
    highlightsEn: ['Golestan Palace', 'National Museum', 'Tajrish Bazaar'],
  },
  {
    id: 'isfahan',
    nameFa: 'اصفهان',
    nameEn: 'Isfahan',
    gradient: 'linear-gradient(135deg,#1B3A6B,#1A7A8A)',
    highlights: ['نقش‌جهان', 'پل خواجو', 'مسجد جامع'],
    highlightsEn: ['Naqsh-e Jahan Square', 'Khaju Bridge', 'Jameh Mosque'],
  },
  {
    id: 'fars',
    nameFa: 'فارس',
    nameEn: 'Fars',
    gradient: 'linear-gradient(135deg,#4A235A,#8B1A1A)',
    highlights: ['تخت‌جمشید', 'حافظیه', 'باغ ارم'],
    highlightsEn: ['Persepolis', 'Hafeziyeh', 'Eram Garden'],
  },
  {
    id: 'khorasan',
    nameFa: 'خراسان رضوی',
    nameEn: 'Khorasan Razavi',
    gradient: 'linear-gradient(135deg,#1A5A2A,#1A7A8A)',
    highlights: ['حرم امام رضا', 'بازار رضا', 'موزه آستان'],
    highlightsEn: ['Imam Reza Shrine', 'Reza Bazaar', 'Astan Quds Museum'],
  },
  {
    id: 'eastazarbaijan',
    nameFa: 'آذربایجان شرقی',
    nameEn: 'East Azerbaijan',
    gradient: 'linear-gradient(135deg,#2E4A8A,#1A7A8A)',
    highlights: ['بازار تاریخی', 'ارگ علیشاه', 'دریاچه ارومیه'],
    highlightsEn: ['Historic Bazaar Tabriz', 'Alishah Arch', 'Lake Urmia'],
  },
  {
    id: 'westazarbaijan',
    nameFa: 'آذربایجان غربی',
    nameEn: 'West Azerbaijan',
    gradient: 'linear-gradient(135deg,#1B3A6B,#2D5A27)',
    highlights: ['دریاچه ارومیه', 'قره‌کلیسا', 'ماکو'],
    highlightsEn: ['Lake Urmia', 'Saint Thaddeus Monastery', 'Maku'],
  },
  {
    id: 'khuzestan',
    nameFa: 'خوزستان',
    nameEn: 'Khuzestan',
    gradient: 'linear-gradient(135deg,#654321,#D4880A)',
    highlights: ['شوشتر', 'چغازنبیل', 'هفت‌تپه'],
    highlightsEn: ['Shushtar Historic Hydraulics', 'Chogha Zanbil', 'Haft Tappeh'],
  },
  {
    id: 'kerman',
    nameFa: 'کرمان',
    nameEn: 'Kerman',
    gradient: 'linear-gradient(135deg,#5C3317,#D4880A)',
    highlights: ['باغ شاهزاده', 'شهر داریوش', 'دشت لوت'],
    highlightsEn: ['Shahzade Garden', 'Arg-e Bam', 'Dasht-e Lut Desert'],
  },
  {
    id: 'gilan',
    nameFa: 'گیلان',
    nameEn: 'Gilan',
    gradient: 'linear-gradient(135deg,#1A5A2A,#2D5A27)',
    highlights: ['جنگل‌های ابری', 'رشت', 'ماسوله'],
    highlightsEn: ['Cloud Forests', 'Rasht City', 'Masuleh Village'],
  },
  {
    id: 'mazandaran',
    nameFa: 'مازندران',
    nameEn: 'Mazandaran',
    gradient: 'linear-gradient(135deg,#1A5A2A,#1A7A8A)',
    highlights: ['جنگل‌های هیرکانی', 'ساری', 'رامسر'],
    highlightsEn: ['Hyrcanian Forests', 'Sari City', 'Ramsar Palaces'],
  },
  {
    id: 'alborz',
    nameFa: 'البرز',
    nameEn: 'Alborz',
    gradient: 'linear-gradient(135deg,#1C1C1E,#1B3A6B)',
    highlights: ['کرج', 'دریاچه قو', 'کوه‌های البرز'],
    highlightsEn: ['Karaj City', 'Swan Lake', 'Alborz Mountain Range'],
  },
  {
    id: 'yazd',
    nameFa: 'یزد',
    nameEn: 'Yazd',
    gradient: 'linear-gradient(135deg,#8B4513,#D4880A)',
    highlights: ['برج‌های باد', 'آتشکده', 'قنات‌های تاریخی'],
    highlightsEn: ['Wind Towers', 'Zoroastrian Fire Temple', 'Ancient Qanats'],
  },
  {
    id: 'qom',
    nameFa: 'قم',
    nameEn: 'Qom',
    gradient: 'linear-gradient(135deg,#1A5A2A,#1B3A6B)',
    highlights: ['حرم معصومه', 'مسجد جمکران', 'حوزه علمیه'],
    highlightsEn: ['Masoumeh Shrine', 'Jamkaran Mosque', 'Islamic Seminary'],
  },
  {
    id: 'semnan',
    nameFa: 'سمنان',
    nameEn: 'Semnan',
    gradient: 'linear-gradient(135deg,#8B4513,#1C1C1E)',
    highlights: ['کویر ملی', 'کاروانسرا', 'شاهرود'],
    highlightsEn: ['Kavir National Park', 'Historic Caravanserai', 'Shahrud'],
  },
  {
    id: 'golestan',
    nameFa: 'گلستان',
    nameEn: 'Golestan',
    gradient: 'linear-gradient(135deg,#2D5A27,#1A7A8A)',
    highlights: ['جنگل گلستان', 'گرگان', 'ترکمن‌صحرا'],
    highlightsEn: ['Golestan Forest', 'Gorgan City', 'Turkmen Steppe'],
  },
  {
    id: 'nkhorasan',
    nameFa: 'خراسان شمالی',
    nameEn: 'North Khorasan',
    gradient: 'linear-gradient(135deg,#654321,#2D5A27)',
    highlights: ['بجنورد', 'قلعه خان', 'دره شاهرود'],
    highlightsEn: ['Bojnurd City', 'Khan Fortress', 'Shahroud Valley'],
  },
  {
    id: 'skhorasan',
    nameFa: 'خراسان جنوبی',
    nameEn: 'South Khorasan',
    gradient: 'linear-gradient(135deg,#5C3317,#8B1A1A)',
    highlights: ['بیرجند', 'قائنات', 'خشاب'],
    highlightsEn: ['Birjand City', 'Qa\'en City', 'Khashab Fortress'],
  },
  {
    id: 'lorestan',
    nameFa: 'لرستان',
    nameEn: 'Lorestan',
    gradient: 'linear-gradient(135deg,#1B3A6B,#2D5A27)',
    highlights: ['آبشار بیشه', 'سد دز', 'خرم‌آباد'],
    highlightsEn: ['Bisheh Waterfall', 'Dez Dam', 'Khorramabad'],
  },
  {
    id: 'ilam',
    nameFa: 'ایلام',
    nameEn: 'Ilam',
    gradient: 'linear-gradient(135deg,#2D5A27,#654321)',
    highlights: ['چشمه دیمه', 'کنگاور', 'شیمبار'],
    highlightsEn: ['Dimeh Spring', 'Kangavar Temple', 'Shimbar Protected Area'],
  },
  {
    id: 'chahar',
    nameFa: 'چهارمحال و بختیاری',
    nameEn: 'Chaharmahal & Bakhtiari',
    gradient: 'linear-gradient(135deg,#1A5A2A,#654321)',
    highlights: ['شهرکرد', 'چلگرد', 'کوه‌رنگ'],
    highlightsEn: ['Shahrekord City', 'Chelgerd Ski Resort', 'Kouhrang Valley'],
  },
  {
    id: 'kohgiluyeh',
    nameFa: 'کهگیلویه و بویراحمد',
    nameEn: 'Kohgiluyeh & Boyer-Ahmad',
    gradient: 'linear-gradient(135deg,#2D5A27,#8B4513)',
    highlights: ['یاسوج', 'دنا', 'تنگ تامرادی'],
    highlightsEn: ['Yasuj City', 'Dena Protected Area', 'Tang Tamradi Canyon'],
  },
  {
    id: 'hormozgan',
    nameFa: 'هرمزگان',
    nameEn: 'Hormozgan',
    gradient: 'linear-gradient(135deg,#006994,#20B2AA)',
    highlights: ['قشم', 'هرمز', 'جنگل حرا'],
    highlightsEn: ['Qeshm Island', 'Hormuz Island', 'Hara Mangrove Forest'],
  },
  {
    id: 'bushehr',
    nameFa: 'بوشهر',
    nameEn: 'Bushehr',
    gradient: 'linear-gradient(135deg,#006994,#1B3A6B)',
    highlights: ['بوشهر', 'عسلویه', 'تنگستان'],
    highlightsEn: ['Bushehr Old City', 'Asaluyeh', 'Tangestan'],
  },
  {
    id: 'zanjan',
    nameFa: 'زنجان',
    nameEn: 'Zanjan',
    gradient: 'linear-gradient(135deg,#1B3A6B,#654321)',
    highlights: ['سلطانیه', 'قافلانکوه', 'زنجان'],
    highlightsEn: ['Soltaniyeh Dome', 'Qaflankouh Mountains', 'Zanjan City'],
  },
  {
    id: 'qazvin',
    nameFa: 'قزوین',
    nameEn: 'Qazvin',
    gradient: 'linear-gradient(135deg,#1B3A6B,#2D5A27)',
    highlights: ['قلعه الموت', 'کاخ چهل ستون', 'بازار قزوین'],
    highlightsEn: ['Alamut Castle', 'Chehel Sotoun Palace Qazvin', 'Qazvin Bazaar'],
  },
  {
    id: 'ardabil',
    nameFa: 'اردبیل',
    nameEn: 'Ardabil',
    gradient: 'linear-gradient(135deg,#2E4A8A,#2D5A27)',
    highlights: ['شیخ صفی‌الدین', 'سبلان', 'سرعین'],
    highlightsEn: ['Sheikh Safi Shrine', 'Sabalan Volcano', 'Sarein Hot Springs'],
  },
  {
    id: 'hamedan',
    nameFa: 'همدان',
    nameEn: 'Hamedan',
    gradient: 'linear-gradient(135deg,#8B1A1A,#1B3A6B)',
    highlights: ['اکباتان', 'آرامگاه بوعلی', 'گنجنامه'],
    highlightsEn: ['Ecbatana Ruins', 'Avicenna Tomb', 'Ganjnameh Inscriptions'],
  },
  {
    id: 'kermanshah',
    nameFa: 'کرمانشاه',
    nameEn: 'Kermanshah',
    gradient: 'linear-gradient(135deg,#654321,#1B3A6B)',
    highlights: ['طاق بستان', 'بیستون', 'کرمانشاه'],
    highlightsEn: ['Taq Bostan Reliefs', 'Bisotun UNESCO Site', 'Kermanshah City'],
  },
  {
    id: 'kurdistan',
    nameFa: 'کردستان',
    nameEn: 'Kurdistan',
    gradient: 'linear-gradient(135deg,#2D5A27,#1B3A6B)',
    highlights: ['سنندج', 'اورامانات', 'مریوان'],
    highlightsEn: ['Sanandaj City', 'Uraman Valley', 'Marivan Lake'],
  },
  {
    id: 'markazi',
    nameFa: 'مرکزی',
    nameEn: 'Markazi',
    gradient: 'linear-gradient(135deg,#1C1C1E,#2D5A27)',
    highlights: ['اراک', 'کارخانه ایران‌خودرو', 'سلطان‌آباد'],
    highlightsEn: ['Arak City', 'Industrial Heritage', 'Sultanabad Carpets'],
  },
  {
    id: 'sistan',
    nameFa: 'سیستان و بلوچستان',
    nameEn: 'Sistan & Baluchestan',
    gradient: 'linear-gradient(135deg,#8B4513,#D4880A)',
    highlights: ['شهر سوخته', 'مکران', 'زاهدان'],
    highlightsEn: ['Shahr-e Sukhteh', 'Makran Coast', 'Zahedan City'],
  },
];

// ─── Traveler Reviews ─────────────────────────────────────────
const REVIEWS = [
  { id:1, name:'Mohamed Al-Rashidi', flag:'🇮🇶', rating:5.0, tripType:'تور معنوی', date:'فروردین ۱۴۰۴',
    text:'بهترین سفر عمرم بود. ایران بسیار زیباتر از آن چیزی بود که فکر می‌کردم. راهنمایان فوق‌العاده و مردم بسیار مهمان‌نواز.',
    avatar:'🧔', avatarGradient:'linear-gradient(135deg,#0D6B8A,#1B3A6B)' },
  { id:2, name:'Ana García', flag:'🇪🇸', rating:5.0, tripType:'Architecture Trail', date:'Bahman 1403',
    text:'Isfahan took my breath away. As an architect, seeing Naqsh-e Jahan Square was a life-changing experience.',
    avatar:'👩', avatarGradient:'linear-gradient(135deg,#4A235A,#8B1A1A)' },
  { id:3, name:'Amir Bin Abdullah', flag:'🇲🇾', rating:4.9, tripType:'Family Journey', date:'Dey 1403',
    text:'Family trip of 8 people, all perfectly organized. The guides were patient, knowledgeable and made us feel so welcome in Iran.',
    avatar:'👨‍👩‍👧', avatarGradient:'linear-gradient(135deg,#1A7A8A,#0F5F6E)' },
  { id:4, name:'Klaus Müller', flag:'🇩🇪', rating:4.8, tripType:'Desert Tour', date:'Azar 1403',
    text:'Die Lut-Wüste bei Nacht war atemberaubend. Iran ist so vielfältig und offen für Besucher.',
    avatar:'👴', avatarGradient:'linear-gradient(135deg,#1B3A6B,#2E6B9E)' },
];

const NAV_ITEMS = [
  { key:'home',         fa:'خانه',              en:'Home' },
  { key:'packages',     fa:'تورها',             en:'Packages' },
  { key:'destinations', fa:'استان‌ها',           en:'Provinces' },
  { key:'guides',       fa:'راهنماها',           en:'Guides' },
  { key:'ai',           fa:'برنامه‌ریز هوشمند', en:'AI Planner' },
];

// ─── AI Conversation (no pricing) ────────────────────────────
const AI_CONVERSATION = [
  { id:1, isUser:false, text:'سلام! من دستیار هوشمند IranTour هستم 🌟\n\nبرای ساختن برنامه سفر ایده‌آل شما، چند سوال کوتاه می‌پرسم. هدف اصلی سفر شما به ایران چیست؟' },
  { id:2, isUser:true,  text:'I\'m an architect visiting for 10 days. Interested in Persian architecture.' },
  { id:3, isUser:false, text:'عالی! انتخاب فوق‌العاده‌ای دارید 🏛️\n\nبرای یک معمار با ۱۰ روز وقت، این مسیر را پیشنهاد می‌کنم:', itinerary:[
    { city:'تهران (روز ۱)',    activity:'موزه ملی ایران، کاخ گلستان' },
    { city:'کاشان (روز ۲-۳)',  activity:'خانه بروجردی‌ها، طباطبایی‌ها' },
    { city:'اصفهان (روز ۴-۶)', activity:'نقش‌جهان، مسجد جامع، پل خواجو' },
    { city:'یزد (روز ۷-۸)',    activity:'معماری بومی، برج‌های باد، بافت تاریخی' },
    { city:'شیراز (روز ۹-۱۰)', activity:'تخت‌جمشید، مسجد نصیرالملک، ارگ کریمخان' },
  ]},
];

Object.assign(window, {
  VISIT_PURPOSES, PACKAGES, GUIDES, GUIDE_REVIEWS, PROVINCES, REVIEWS, NAV_ITEMS, AI_CONVERSATION
});
