// IranTour Advisor — Data v2 (no pricing, 31 provinces, new guides/packages)

// ─── Visit Purpose Categories ───────────────────────────────
const VISIT_PURPOSES = [
  { key: 'tourism',   faIcon: '🎭', fa: 'گردشگری و تفریح',     en: 'Tourism & Leisure' },
  { key: 'business',  faIcon: '💼', fa: 'سفر تجاری',             en: 'Business Trip' },
  { key: 'academic',  faIcon: '🔬', fa: 'پژوهش دانشگاهی',       en: 'Academic Research' },
  { key: 'media',     faIcon: '📸', fa: 'عکاسی و رسانه',         en: 'Photography & Media' },
  { key: 'religious', faIcon: '🕌', fa: 'سفر زیارتی',             en: 'Religious Journey' },
  { key: 'nature',    faIcon: '🌿', fa: 'طبیعت و ماجراجویی',    en: 'Nature & Adventure' },
  { key: 'arts',      faIcon: '🎨', fa: 'هنر و فرهنگ',           en: 'Arts & Culture' },
  { key: 'family',    faIcon: '👨‍👩‍👧', fa: 'سفر خانوادگی',    en: 'Family Travel' },
];

// ─── Tour Packages v2 (no pricing, multi-city only) ─────────
const PACKAGES = [
  {
    id: 1,
    nameFa: 'مسیر معماری پارسی',
    nameEn: 'Persian Architecture Trail',
    cities: ['اصفهان', 'کاشان', 'یزد', 'شیراز'],
    citiesEn: ['Isfahan', 'Kashan', 'Yazd', 'Shiraz'],
    days: 10,
    difficulty: 'easy',
    rating: 4.9, reviews: 284,
    purposes: ['tourism', 'academic', 'arts', 'media'],
    gradient: 'linear-gradient(135deg, #1B3A6B 0%, #2E6B9E 40%, #8B1A1A 100%)',
    tagFa: 'معماری اسلامی',
    tagEn: 'Islamic Architecture',
    descFa: 'سفر در میان شاهکارهای معماری اسلامی ایران از میدان نقش‌جهان تا خانه‌های تاریخی کاشان',
    descEn: 'Journey through Iran\'s Islamic architecture masterpieces from Naqsh-e Jahan to Kashan\'s historic houses',
    highlights: ['نقش‌جهان', 'خانه بروجردی‌ها', 'تخت جمشید', 'برج‌های باد'],
    highlightsEn: ['Naqsh-e Jahan', 'Borujerdi House', 'Persepolis', 'Wind Towers'],
  },
  {
    id: 2,
    nameFa: 'جاده ابریشم',
    nameEn: 'Silk Road Heritage Journey',
    cities: ['یزد', 'کرمان', 'خراسان جنوبی'],
    citiesEn: ['Yazd', 'Kerman', 'South Khorasan'],
    days: 8,
    difficulty: 'medium',
    rating: 4.8, reviews: 196,
    purposes: ['academic', 'tourism', 'media', 'arts'],
    gradient: 'linear-gradient(135deg, #8B4513 0%, #D4880A 50%, #2D5A27 100%)',
    tagFa: 'میراث تاریخی',
    tagEn: 'Historic Heritage',
    descFa: 'ردپای کاروان‌های باستانی در شهرهای جاده ابریشم ایران',
    descEn: 'Trace ancient caravan routes through Iran\'s Silk Road cities',
    highlights: ['برج‌های باد یزد', 'بازار وکیل', 'باغ شاهزاده'],
    highlightsEn: ['Yazd Wind Towers', 'Vakil Bazaar', 'Shahzade Garden'],
  },
  {
    id: 3,
    nameFa: 'دنیای ادبیات پارسی',
    nameEn: 'Persian Literary World',
    cities: ['شیراز', 'نیشابور'],
    citiesEn: ['Shiraz', 'Nishapur'],
    days: 6,
    difficulty: 'easy',
    rating: 4.7, reviews: 143,
    purposes: ['academic', 'tourism', 'arts'],
    gradient: 'linear-gradient(135deg, #4A235A 0%, #1B3A6B 50%, #8B1A1A 100%)',
    tagFa: 'ادبیات کلاسیک',
    tagEn: 'Classical Literature',
    descFa: 'در آغوش حافظ، سعدی و خیام — سفری در قلب شعر پارسی',
    descEn: 'In the embrace of Hafez, Saadi and Khayyam — a journey into Persian poetry',
    highlights: ['حافظیه', 'سعدیه', 'آرامگاه خیام'],
    highlightsEn: ['Hafeziyeh', 'Saadieh', 'Omar Khayyam Tomb'],
  },
  {
    id: 4,
    nameFa: 'شگفتی‌های کویر و تمدن‌های باستانی',
    nameEn: 'Desert Wonders & Ancient Civilizations',
    cities: ['یزد', 'دشت لوت', 'سمنان'],
    citiesEn: ['Yazd', 'Dasht-e Lut', 'Semnan'],
    days: 7,
    difficulty: 'medium',
    rating: 4.9, reviews: 228,
    purposes: ['nature', 'media', 'academic', 'tourism'],
    gradient: 'linear-gradient(135deg, #0D1B2A 0%, #1B3A6B 40%, #8B4513 100%)',
    tagFa: 'طبیعت و کویر',
    tagEn: 'Nature & Desert',
    descFa: 'شب‌های جادویی دشت لوت، معماری بومی یزد و رازهای کویر ایران',
    descEn: 'Magical nights in Dasht-e Lut, vernacular architecture of Yazd and the secrets of Iran\'s desert',
    highlights: ['دشت لوت', 'برج‌های باد', 'رصد ستارگان'],
    highlightsEn: ['Dasht-e Lut', 'Wind Towers', 'Stargazing'],
  },
  {
    id: 5,
    nameFa: 'میراث صنعتی و مدرن ایران',
    nameEn: 'Iranian Industrial & Modern Heritage',
    cities: ['اصفهان', 'اراک', 'تهران'],
    citiesEn: ['Isfahan', 'Arak', 'Tehran'],
    days: 6,
    difficulty: 'easy',
    rating: 4.5, reviews: 89,
    purposes: ['business', 'academic', 'tourism'],
    gradient: 'linear-gradient(135deg, #1C1C1E 0%, #1B3A6B 50%, #2D5A27 100%)',
    tagFa: 'صنعت و مدرنیته',
    tagEn: 'Industry & Modernity',
    descFa: 'کشف ایران مدرن از کارخانه‌های تاریخی اراک تا استارتاپ‌های تهران',
    descEn: 'Discover modern Iran from Arak\'s historic factories to Tehran\'s startup scene',
    highlights: ['گالری‌های هنری تهران', 'کارخانه‌های اراک', 'نیاوران'],
    highlightsEn: ['Tehran Art Galleries', 'Arak Factories', 'Niavaran'],
  },
  {
    id: 6,
    nameFa: 'جهان شیعی و اماکن مقدس',
    nameEn: 'Shia World & Religious Sites',
    cities: ['مشهد', 'قم', 'تهران'],
    citiesEn: ['Mashhad', 'Qom', 'Tehran'],
    days: 7,
    difficulty: 'easy',
    rating: 4.8, reviews: 317,
    purposes: ['religious', 'academic', 'tourism'],
    gradient: 'linear-gradient(135deg, #1A5A2A 0%, #1A7A8A 40%, #1B3A6B 100%)',
    tagFa: 'زیارتی',
    tagEn: 'Religious Pilgrimage',
    descFa: 'سفر معنوی به قلب جهان شیعه — از حرم امام رضا تا حوزه علمیه قم',
    descEn: 'Spiritual journey to the heart of the Shia world — from Imam Reza shrine to Qom seminary',
    highlights: ['حرم امام رضا', 'حرم معصومه', 'مسجد جمکران'],
    highlightsEn: ['Imam Reza Shrine', 'Masoumeh Shrine', 'Jamkaran Mosque'],
  },
];

// ─── 3 Default Guides ────────────────────────────────────────
const GUIDES = [
  {
    id: 1,
    nameFa: 'سارا محمدی',
    nameEn: 'Sara Mohammadi',
    city: 'شیراز',
    cityEn: 'Shiraz',
    specialtyFa: 'شعر پارسی و معماری کلاسیک',
    specialtyEn: 'Persian Poetry & Classical Architecture',
    rating: 4.8, reviews: 47,
    experience: 8,
    languages: [
      { code: 'en', flag: '🇬🇧', name: 'English' },
      { code: 'fr', flag: '🇫🇷', name: 'Français' },
    ],
    bioFa: 'با بیش از ۸ سال تجربه راهنمایی در شیراز، تخصصم در شعر کلاسیک فارسی و معماری تاریخی این شهر است. هر تور با من یک سفر ادبی و فرهنگی است.',
    bioEn: 'With over 8 years of guiding in Shiraz, I specialize in classical Persian poetry and the city\'s historic architecture. Every tour with me is a literary and cultural journey.',
    activities: [
      { fa: 'بازدید از آرامگاه حافظ', en: 'Hafez tomb visit', icon: '📜' },
      { fa: 'تور روزانه تخت‌جمشید', en: 'Persepolis day trip', icon: '🏛️' },
      { fa: 'طلوع آفتاب در مسجد نصیرالملک', en: 'Nasir ol-Molk Mosque at sunrise', icon: '🕌' },
      { fa: 'بازار سنتی شیراز', en: 'Traditional Shiraz bazaar tour', icon: '🛍️' },
      { fa: 'کارگاه خوشنویسی فارسی', en: 'Persian calligraphy workshop', icon: '✍️' },
    ],
    contact: { email: 'sara@irantour.ir', phone: '+98 917 123 4567', instagram: '@sara_shiraz_guide', telegram: '@sara_shiraz' },
    avatarColor: '#8B1A1A',
    carpetPattern: 'shiraz',
  },
  {
    id: 2,
    nameFa: 'رضا احمدی',
    nameEn: 'Reza Ahmadi',
    city: 'اصفهان',
    cityEn: 'Isfahan',
    specialtyFa: 'معماری اسلامی و هنرهای ایرانی',
    specialtyEn: 'Islamic Architecture & Persian Arts',
    rating: 4.9, reviews: 63,
    experience: 12,
    languages: [
      { code: 'en', flag: '🇬🇧', name: 'English' },
      { code: 'ar', flag: '🇸🇦', name: 'العربية' },
    ],
    bioFa: 'کارشناس ارشد معماری اسلامی و راهنمای تخصصی اصفهان. با ۱۲ سال تجربه، هر گوشه از نقش‌جهان برایم یک داستان دارد.',
    bioEn: 'Master\'s in Islamic architecture and specialized Isfahan guide. With 12 years of experience, every corner of Naqsh-e Jahan has a story for me.',
    activities: [
      { fa: 'میدان نقش‌جهان', en: 'Naqsh-e Jahan Square', icon: '🏟️' },
      { fa: 'مسجد شیخ لطف‌الله', en: 'Sheikh Lotfollah Mosque', icon: '🕌' },
      { fa: 'محله ارامنه', en: 'Armenian Quarter', icon: '⛪' },
      { fa: 'کارگاه سنتی قالی‌بافی', en: 'Traditional carpet workshop', icon: '🪡' },
      { fa: 'کاخ چهل‌ستون', en: 'Chehel Sotoun Palace', icon: '🏛️' },
    ],
    contact: { email: 'reza@irantour.ir', phone: '+98 913 234 5678', instagram: '@reza_isfahan', telegram: '@reza_arhitecture' },
    avatarColor: '#1B3A6B',
    carpetPattern: 'isfahan',
  },
  {
    id: 3,
    nameFa: 'مریم حسینی',
    nameEn: 'Maryam Hosseini',
    city: 'یزد',
    cityEn: 'Yazd',
    specialtyFa: 'تمدن باستانی کویر و فرهنگ زرتشتی',
    specialtyEn: 'Ancient Desert Civilization & Zoroastrian Culture',
    rating: 4.7, reviews: 38,
    experience: 7,
    languages: [
      { code: 'en', flag: '🇬🇧', name: 'English' },
      { code: 'de', flag: '🇩🇪', name: 'Deutsch' },
    ],
    bioFa: 'متخصص تاریخ و فرهنگ زرتشتی در یزد. تورهایم ترکیبی از تاریخ باستانی، معماری بومی کویر و شب‌های پر ستاره صحرا است.',
    bioEn: 'Specialist in Zoroastrian history and culture in Yazd. My tours combine ancient history, desert vernacular architecture and star-filled desert nights.',
    activities: [
      { fa: 'باغ دولت‌آباد و بادگیرها', en: 'Dowlatabad Garden windtowers', icon: '🌬️' },
      { fa: 'بازدید آتشکده زرتشتی', en: 'Fire Temple visit', icon: '🔥' },
      { fa: 'پیاده‌روی در کوچه‌های قدیمی', en: 'Old city labyrinth walk', icon: '🚶' },
      { fa: 'کارگاه شیرینی سنتی یزدی', en: 'Traditional Yazdi pastry making', icon: '🍰' },
      { fa: 'رصد ستارگان در کویر', en: 'Desert night stargazing', icon: '⭐' },
    ],
    contact: { email: 'maryam@irantour.ir', phone: '+98 935 345 6789', instagram: '@maryam_yazd', telegram: '@maryam_desert' },
    avatarColor: '#2D5A27',
    carpetPattern: 'yazd',
  },
];

// ─── Guide Reviews ────────────────────────────────────────────
const GUIDE_REVIEWS = {
  1: [
    { name: 'Ana García', flag: '🇪🇸', date: 'فروردین ۱۴۰۴', rating: 5, text: 'Sara made Shiraz come alive for me. Her knowledge of Persian poetry is extraordinary.' },
    { name: 'Klaus Müller', flag: '🇩🇪', date: 'بهمن ۱۴۰۳', rating: 5, text: 'The sunrise at Nasir al-Mulk mosque was the most beautiful thing I\'ve ever seen.' },
    { name: 'Mohamed Al-Rashidi', flag: '🇮🇶', date: 'دی ۱۴۰۳', rating: 4.5, text: 'سارا راهنمای فوق‌العاده‌ای است. شیراز را با چشمان تازه دیدم.' },
  ],
  2: [
    { name: 'Yuki Tanaka', flag: '🇯🇵', date: 'اردیبهشت ۱۴۰۴', rating: 5, text: 'Reza\'s architectural knowledge is unmatched. The details he notices in Naqsh-e Jahan are incredible.' },
    { name: 'Fatima Al-Hassan', flag: '🇸🇦', date: 'فروردین ۱۴۰۴', rating: 5, text: 'رضا بهترین راهنمایی بود که در اصفهان داشتم. معلومات بسیار عمیق دارد.' },
    { name: 'Pierre Dubois', flag: '🇫🇷', date: 'اسفند ۱۴۰۳', rating: 5, text: 'I came for architecture and left with a profound understanding of Islamic art.' },
  ],
  3: [
    { name: 'Emma Schmidt', flag: '🇩🇪', date: 'فروردین ۱۴۰۴', rating: 5, text: 'Maryam\'s passion for Zoroastrian culture is infectious. The stargazing was magical.' },
    { name: 'David Chen', flag: '🇨🇳', date: 'بهمن ۱۴۰۳', rating: 4.5, text: 'Yazd through Maryam\'s eyes is a completely different experience. Highly recommended.' },
    { name: 'Layla Hassan', flag: '🇪🇬', date: 'آذر ۱۴۰۳', rating: 4.5, text: 'مریم با صبر و علم فراوان هر چیزی را توضیح داد. سفر فراموش‌نشدنی.' },
  ],
};

// ─── 31 Provinces of Iran ─────────────────────────────────────
const PROVINCES = [
  { id: 'tehran',        nameFa: 'تهران',                   nameEn: 'Tehran',                   gradient: 'linear-gradient(135deg,#1C1C1E,#8B1A1A)', highlights: ['کاخ گلستان','موزه ملی','بازار تجریش'] },
  { id: 'isfahan',       nameFa: 'اصفهان',                  nameEn: 'Isfahan',                  gradient: 'linear-gradient(135deg,#1B3A6B,#1A7A8A)', highlights: ['نقش‌جهان','پل خواجو','مسجد جامع'] },
  { id: 'fars',          nameFa: 'فارس',                    nameEn: 'Fars',                     gradient: 'linear-gradient(135deg,#4A235A,#8B1A1A)', highlights: ['تخت‌جمشید','حافظیه','باغ ارم'] },
  { id: 'khorasan',      nameFa: 'خراسان رضوی',             nameEn: 'Khorasan Razavi',          gradient: 'linear-gradient(135deg,#1A5A2A,#1A7A8A)', highlights: ['حرم امام رضا','بازار رضا','موزه آستان'] },
  { id: 'eastazarbaijan',nameFa: 'آذربایجان شرقی',          nameEn: 'East Azerbaijan',          gradient: 'linear-gradient(135deg,#2E4A8A,#1A7A8A)', highlights: ['بازار تاریخی','ارگ علیشاه','دریاچه ارومیه'] },
  { id: 'westazarbaijan',nameFa: 'آذربایجان غربی',          nameEn: 'West Azerbaijan',          gradient: 'linear-gradient(135deg,#1B3A6B,#2D5A27)', highlights: ['دریاچه ارومیه','قره‌کلیسا','ماکو'] },
  { id: 'khuzestan',     nameFa: 'خوزستان',                 nameEn: 'Khuzestan',                gradient: 'linear-gradient(135deg,#654321,#D4880A)', highlights: ['شوشتر','چغازنبیل','هفت‌تپه'] },
  { id: 'kerman',        nameFa: 'کرمان',                   nameEn: 'Kerman',                   gradient: 'linear-gradient(135deg,#5C3317,#D4880A)', highlights: ['باغ شاهزاده','شهر داریوش','دشت لوت'] },
  { id: 'gilan',         nameFa: 'گیلان',                   nameEn: 'Gilan',                    gradient: 'linear-gradient(135deg,#1A5A2A,#2D5A27)', highlights: ['جنگل‌های ابری','رشت','ماسوله'] },
  { id: 'mazandaran',    nameFa: 'مازندران',                nameEn: 'Mazandaran',               gradient: 'linear-gradient(135deg,#1A5A2A,#1A7A8A)', highlights: ['جنگل‌های هیرکانی','ساری','رامسر'] },
  { id: 'alborz',        nameFa: 'البرز',                   nameEn: 'Alborz',                   gradient: 'linear-gradient(135deg,#1C1C1E,#1B3A6B)', highlights: ['کرج','دریاچه قو','کوه‌های البرز'] },
  { id: 'yazd',          nameFa: 'یزد',                     nameEn: 'Yazd',                     gradient: 'linear-gradient(135deg,#8B4513,#D4880A)', highlights: ['برج‌های باد','آتشکده','قنات‌های تاریخی'] },
  { id: 'qom',           nameFa: 'قم',                      nameEn: 'Qom',                      gradient: 'linear-gradient(135deg,#1A5A2A,#1B3A6B)', highlights: ['حرم معصومه','مسجد جمکران','حوزه علمیه'] },
  { id: 'semnan',        nameFa: 'سمنان',                   nameEn: 'Semnan',                   gradient: 'linear-gradient(135deg,#8B4513,#1C1C1E)', highlights: ['کویر ملی','کاروانسرا','شاهرود'] },
  { id: 'golestan',      nameFa: 'گلستان',                  nameEn: 'Golestan',                 gradient: 'linear-gradient(135deg,#2D5A27,#1A7A8A)', highlights: ['جنگل گلستان','گرگان','ترکمن‌صحرا'] },
  { id: 'nkhorasan',     nameFa: 'خراسان شمالی',            nameEn: 'North Khorasan',           gradient: 'linear-gradient(135deg,#654321,#2D5A27)', highlights: ['بجنورد','قلعه خان','دره شاهرود'] },
  { id: 'skhorasan',     nameFa: 'خراسان جنوبی',            nameEn: 'South Khorasan',           gradient: 'linear-gradient(135deg,#5C3317,#8B1A1A)', highlights: ['بیرجند','قائنات','خشاب'] },
  { id: 'lorestan',      nameFa: 'لرستان',                  nameEn: 'Lorestan',                 gradient: 'linear-gradient(135deg,#1B3A6B,#2D5A27)', highlights: ['آبشار بیشه','سد دز','خرم‌آباد'] },
  { id: 'ilam',          nameFa: 'ایلام',                   nameEn: 'Ilam',                     gradient: 'linear-gradient(135deg,#2D5A27,#654321)', highlights: ['چشمه دیمه','کنگاور','شیمبار'] },
  { id: 'chahar',        nameFa: 'چهارمحال و بختیاری',     nameEn: 'Chaharmahal & Bakhtiari',  gradient: 'linear-gradient(135deg,#1A5A2A,#654321)', highlights: ['شهرکرد','چلگرد','کوه‌رنگ'] },
  { id: 'kohgiluyeh',    nameFa: 'کهگیلویه و بویراحمد',    nameEn: 'Kohgiluyeh & Boyer-Ahmad', gradient: 'linear-gradient(135deg,#2D5A27,#8B4513)', highlights: ['یاسوج','دنا','تنگ تامرادی'] },
  { id: 'hormozgan',     nameFa: 'هرمزگان',                 nameEn: 'Hormozgan',                gradient: 'linear-gradient(135deg,#006994,#20B2AA)', highlights: ['قشم','هرمز','جنگل حرا'] },
  { id: 'bushehr',       nameFa: 'بوشهر',                   nameEn: 'Bushehr',                  gradient: 'linear-gradient(135deg,#006994,#1B3A6B)', highlights: ['بوشهر','عسلویه','تنگستان'] },
  { id: 'zanjan',        nameFa: 'زنجان',                   nameEn: 'Zanjan',                   gradient: 'linear-gradient(135deg,#1B3A6B,#654321)', highlights: ['سلطانیه','قافلانکوه','زنجان'] },
  { id: 'qazvin',        nameFa: 'قزوین',                   nameEn: 'Qazvin',                   gradient: 'linear-gradient(135deg,#1B3A6B,#2D5A27)', highlights: ['قلعه الموت','کاخ چهل ستون','بازار قزوین'] },
  { id: 'ardabil',       nameFa: 'اردبیل',                  nameEn: 'Ardabil',                  gradient: 'linear-gradient(135deg,#2E4A8A,#2D5A27)', highlights: ['شیخ صفی‌الدین','سبلان','سرعین'] },
  { id: 'hamedan',       nameFa: 'همدان',                   nameEn: 'Hamedan',                  gradient: 'linear-gradient(135deg,#8B1A1A,#1B3A6B)', highlights: ['اکباتان','آرامگاه بوعلی','گنجنامه'] },
  { id: 'kermanshah',    nameFa: 'کرمانشاه',                nameEn: 'Kermanshah',               gradient: 'linear-gradient(135deg,#654321,#1B3A6B)', highlights: ['طاق بستان','بیستون','کرمانشاه'] },
  { id: 'kurdistan',     nameFa: 'کردستان',                 nameEn: 'Kurdistan',                gradient: 'linear-gradient(135deg,#2D5A27,#1B3A6B)', highlights: ['سنندج','اورامانات','مریوان'] },
  { id: 'markazi',       nameFa: 'مرکزی',                   nameEn: 'Markazi',                  gradient: 'linear-gradient(135deg,#1C1C1E,#2D5A27)', highlights: ['اراک','کارخانه ایران‌خودرو','سلطان‌آباد'] },
  { id: 'sistan',        nameFa: 'سیستان و بلوچستان',       nameEn: 'Sistan & Baluchestan',     gradient: 'linear-gradient(135deg,#8B4513,#D4880A)', highlights: ['شهر سوخته','مکران','زاهدان'] },
];

// ─── Traveler Reviews ─────────────────────────────────────────
const REVIEWS = [
  { id:1, name:'Mohamed Al-Rashidi', flag:'🇮🇶', rating:5.0, tripType:'تور معنوی', date:'فروردین ۱۴۰۴',
    text:'بهترین سفر عمرم بود. ایران بسیار زیباتر از آن چیزی بود که فکر می‌کردم. راهنمایان فوق‌العاده و مردم بسیار مهمان‌نواز.',
    avatar:'🧔', avatarGradient:'linear-gradient(135deg,#0D6B8A,#1B3A6B)' },
  { id:2, name:'Ana García', flag:'🇪🇸', rating:5.0, tripType:'Architecture Trail', date:'Bahman 1403',
    text:'Isfahan took my breath away. As an architect, seeing Naqsh-e Jahan Square was a life-changing experience.',
    avatar:'👩', avatarGradient:'linear-gradient(135deg,#4A235A,#8B1A1A)' },
  { id:3, name:'Amir Bin Abdullah', flag:'🇲🇾', rating:4.9, tripType:'Family Journey', date:'Dey 1403',
    text:'Family trip of 8 people, all perfectly organized. The guides were patient, knowledgeable and made us feel so welcome in Iran.',
    avatar:'👨‍👩‍👧', avatarGradient:'linear-gradient(135deg,#1A7A8A,#0F5F6E)' },
  { id:4, name:'Klaus Müller', flag:'🇩🇪', rating:4.8, tripType:'Desert Tour', date:'Azar 1403',
    text:'Die Lut-Wüste bei Nacht war atemberaubend. Iran ist so vielfältig und offen für Besucher.',
    avatar:'👴', avatarGradient:'linear-gradient(135deg,#1B3A6B,#2E6B9E)' },
];

const NAV_ITEMS = [
  { key:'home',         fa:'خانه',              en:'Home' },
  { key:'packages',     fa:'تورها',             en:'Packages' },
  { key:'destinations', fa:'استان‌ها',           en:'Provinces' },
  { key:'guides',       fa:'راهنماها',           en:'Guides' },
  { key:'ai',           fa:'برنامه‌ریز هوشمند', en:'AI Planner' },
];

// ─── AI Conversation (no pricing) ────────────────────────────
const AI_CONVERSATION = [
  { id:1, isUser:false, text:'سلام! من دستیار هوشمند IranTour هستم 🌟\n\nبرای ساختن برنامه سفر ایده‌آل شما، چند سوال کوتاه می‌پرسم. هدف اصلی سفر شما به ایران چیست؟' },
  { id:2, isUser:true,  text:'I\'m an architect visiting for 10 days. Interested in Persian architecture.' },
  { id:3, isUser:false, text:'عالی! انتخاب فوق‌العاده‌ای دارید 🏛️\n\nبرای یک معمار با ۱۰ روز وقت، این مسیر را پیشنهاد می‌کنم:', itinerary:[
    { city:'تهران (روز ۱)',    activity:'موزه ملی ایران، کاخ گلستان' },
    { city:'کاشان (روز ۲-۳)',  activity:'خانه بروجردی‌ها، طباطبایی‌ها' },
    { city:'اصفهان (روز ۴-۶)', activity:'نقش‌جهان، مسجد جامع، پل خواجو' },
    { city:'یزد (روز ۷-۸)',    activity:'معماری بومی، برج‌های باد، بافت تاریخی' },
    { city:'شیراز (روز ۹-۱۰)', activity:'تخت‌جمشید، مسجد نصیرالملک، ارگ کریمخان' },
  ]},
];

Object.assign(window, {
  VISIT_PURPOSES, PACKAGES, GUIDES, GUIDE_REVIEWS, PROVINCES, REVIEWS, NAV_ITEMS, AI_CONVERSATION
});
